# Generated by Django 5.0 on 2026-02-07 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, choices=[('student', 'Öğrenci'), ('researcher', 'Araştırmacı'), ('professor', 'Profesör/Akademisyen'), ('engineer', 'Mühendis'), ('developer', 'Yazılım Geliştirici'), ('data_scientist', 'Veri Bilimci'), ('doctor', 'Doktor'), ('lawyer', 'Avukat'), ('teacher', 'Öğretmen'), ('business', 'İş İnsanı'), ('freelancer', 'Serbest Çalışan'), ('other', 'Diğer')], max_length=50)),
                ('profession_detail', models.CharField(blank=True, help_text='Meslek detayı', max_length=200)),
                ('company_or_institution', models.CharField(blank=True, help_text='Şirket veya kurum', max_length=200)),
                ('education_level', models.CharField(blank=True, choices=[('high_school', 'Lise'), ('associate', 'Ön Lisans'), ('bachelor', 'Lisans'), ('master', 'Yüksek Lisans'), ('phd', 'Doktora'), ('postdoc', 'Post-Doktora')], max_length=20)),
                ('field_of_study', models.CharField(blank=True, help_text='Mezuniyet/Okuma alanı', max_length=200)),
                ('university', models.CharField(blank=True, help_text='Üniversite', max_length=200)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, help_text='Kısa biyografi', max_length=500)),
                ('interests', models.JSONField(default=list, help_text='İlgi alanları listesi')),
                ('research_areas', models.JSONField(default=list, help_text='Araştırma alanları')),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('orcid', models.CharField(blank=True, help_text='ORCID ID', max_length=50)),
                ('google_scholar', models.URLField(blank=True)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('avatar_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
    ]
