# Generated by Django 6.0.2 on 2026-03-08 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('api_collecter', '0003_proxykonfig_scrapeicerik_scrapelogu_scraperkonfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=1000)),
                ('abstract', models.TextField(blank=True, default='')),
                ('authors', models.JSONField(default=list)),
                ('published_date', models.CharField(blank=True, default='', max_length=50)),
                ('journal', models.CharField(blank=True, default='', max_length=500)),
                ('url', models.URLField(blank=True, default='', max_length=2000)),
                ('pdf_url', models.URLField(blank=True, default='', max_length=2000)),
                ('doi', models.CharField(blank=True, default='', max_length=200)),
                ('source_name', models.CharField(blank=True, default='', max_length=100)),
                ('categories', models.JSONField(default=list)),
                ('citation_count', models.IntegerField(default=0)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_by', to='api_collecter.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kaydedilen Makale',
                'verbose_name_plural': 'Kaydedilen Makaleler',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'external_id')},
            },
        ),
    ]
