# Generated by Django 6.0.2 on 2026-04-02 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_savedarticle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('search', 'Arama'), ('save', 'Kaydetme'), ('remove_save', 'Kaydetmeyi Geri Alma'), ('view', 'Görüntüleme'), ('profile_update', 'Profil Güncelleme')], max_length=20)),
                ('content_title', models.CharField(blank=True, help_text='Makale başlığı veya arama terimi', max_length=1000)),
                ('content_id', models.CharField(blank=True, help_text="Makale ID'si veya URL'si", max_length=500)),
                ('query', models.TextField(blank=True, help_text='Yapılan arama sorgusu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Aktivitesi',
                'verbose_name_plural': 'Kullanıcı Aktiviteleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
