# Generated by Django 6.0.2 on 2026-03-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_collecter', '0003_proxykonfig_scrapeicerik_scrapelogu_scraperkonfig_and_more'),
        ('webscraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaydedilenIcerik',
            fields=[
            ],
            options={
                'verbose_name': 'Scrape Edilen İçerik',
                'verbose_name_plural': 'Scrape Edilen İçerikler',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('webscraping.scrapedcontent',),
        ),
        migrations.CreateModel(
            name='KaydedilenMakale',
            fields=[
            ],
            options={
                'verbose_name': 'Makale',
                'verbose_name_plural': 'Makaleler',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api_collecter.article',),
        ),
    ]
