# Generated by Django 5.0 on 2025-12-25 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this callback', max_length=100, unique=True)),
                ('endpoint_url', models.URLField(help_text='URL to send callbacks to')),
                ('webhook_secret', models.CharField(help_text='Secret key for webhook validation', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this callback')),
                ('retry_count', models.IntegerField(default=3, help_text='Number of retry attempts on failure')),
                ('timeout_seconds', models.IntegerField(default=30, help_text='Request timeout in seconds')),
                ('trigger_on_new_content', models.BooleanField(default=True)),
                ('trigger_on_scrape_complete', models.BooleanField(default=False)),
                ('trigger_on_errors', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Callback Configuration',
                'verbose_name_plural': 'Callback Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Source of the webhook', max_length=100)),
                ('payload', models.JSONField(help_text='Received webhook payload')),
                ('headers', models.JSONField(help_text='Request headers')),
                ('validated', models.BooleanField(default=False, help_text='Whether webhook signature was validated')),
                ('processed', models.BooleanField(default=False, help_text='Whether payload was processed')),
                ('processing_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook Receiver',
                'verbose_name_plural': 'Webhook Receivers',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='CallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Type of event that triggered callback', max_length=50)),
                ('request_payload', models.JSONField(help_text='Data sent to callback endpoint')),
                ('response_status', models.IntegerField(blank=True, help_text='HTTP status code', null=True)),
                ('response_body', models.TextField(blank=True, help_text='Response from endpoint')),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('retry_attempt', models.IntegerField(default=0, help_text='Current retry attempt number')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api_collecter.callbackconfig')),
            ],
            options={
                'verbose_name': 'Callback Log',
                'verbose_name_plural': 'Callback Logs',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['success', '-attempted_at'], name='api_collecter_success_idx'), models.Index(fields=['config', '-attempted_at'], name='api_collecter_config_idx')],
            },
        ),
    ]
