# Generated by Django 5.0 on 2026-02-07 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_collecter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Başladı'), ('fetching', 'Çekiliyor'), ('processing', 'İşleniyor'), ('success', 'Başarılı'), ('partial', 'Kısmi Başarı'), ('failed', 'Başarısız'), ('cancelled', 'İptal Edildi')], default='started', max_length=20)),
                ('request_url', models.TextField(blank=True, help_text="Yapılan istek URL'i")),
                ('request_params', models.JSONField(blank=True, default=dict, help_text='İstek parametreleri')),
                ('articles_found', models.IntegerField(default=0, help_text='Bulunan makale sayısı')),
                ('articles_saved', models.IntegerField(default=0, help_text='Kaydedilen makale sayısı')),
                ('articles_updated', models.IntegerField(default=0, help_text='Güncellenen makale sayısı')),
                ('articles_skipped', models.IntegerField(default=0, help_text='Atlanan makale sayısı (duplicate)')),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='Detaylı hata bilgisi')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'API Çekme Logu',
                'verbose_name_plural': 'API Çekme Logları',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='APISourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='API kaynağı için benzersiz isim', max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('arxiv', 'arXiv API'), ('openalex', 'OpenAlex API'), ('crossref', 'CrossRef API'), ('semantic_scholar', 'Semantic Scholar API'), ('pubmed', 'PubMed API'), ('ieee', 'IEEE Xplore API'), ('springer', 'Springer Nature API'), ('core', 'CORE API'), ('doaj', 'DOAJ API'), ('custom', 'Custom API')], help_text='API türü', max_length=50)),
                ('base_url', models.URLField(help_text='API base URL')),
                ('api_key', models.CharField(blank=True, help_text='API anahtarı (gerekiyorsa)', max_length=500)),
                ('api_secret', models.CharField(blank=True, help_text='API secret (gerekiyorsa)', max_length=500)),
                ('search_query', models.TextField(blank=True, help_text='Varsayılan arama sorgusu/anahtar kelimeler')),
                ('categories', models.TextField(blank=True, help_text='Kategoriler (virgülle ayrılmış)')),
                ('max_results_per_request', models.IntegerField(default=100, help_text='İstek başına maksimum sonuç')),
                ('rate_limit_per_minute', models.IntegerField(default=60, help_text='Dakikada maksimum istek sayısı')),
                ('fetch_interval_hours', models.IntegerField(default=6, help_text='Kaç saatte bir çekilecek')),
                ('is_active', models.BooleanField(default=True, help_text='Aktif/Pasif')),
                ('last_fetch', models.DateTimeField(blank=True, help_text='Son başarılı çekme zamanı', null=True)),
                ('next_fetch', models.DateTimeField(blank=True, help_text='Sonraki planlanan çekme', null=True)),
                ('total_articles_fetched', models.IntegerField(default=0, help_text='Toplam çekilen makale sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Kaynak Konfigürasyonu',
                'verbose_name_plural': 'API Kaynak Konfigürasyonları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Kaynak sistemdeki ID', max_length=255, unique=True)),
                ('title', models.TextField(help_text='Makale başlığı')),
                ('abstract', models.TextField(blank=True, help_text='Özet')),
                ('authors', models.JSONField(default=list, help_text='Yazarlar listesi')),
                ('published_date', models.DateField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=500)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('doi', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('url', models.URLField(blank=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('categories', models.JSONField(default=list, help_text='Kategoriler')),
                ('keywords', models.JSONField(default=list, help_text='Anahtar kelimeler')),
                ('citation_count', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(default=dict, help_text='Orijinal API yanıtı')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Makale',
                'verbose_name_plural': 'Makaleler',
                'ordering': ['-published_date', '-fetched_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='callbacklog',
            new_name='api_collect_success_590139_idx',
            old_name='api_collecter_success_idx',
        ),
        migrations.RenameIndex(
            model_name='callbacklog',
            new_name='api_collect_config__bdcc24_idx',
            old_name='api_collecter_config_idx',
        ),
        migrations.AddField(
            model_name='apifetchlog',
            name='api_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='api_collecter.apisourceconfig'),
        ),
        migrations.AddField(
            model_name='article',
            name='api_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='api_collecter.apisourceconfig'),
        ),
        migrations.AddIndex(
            model_name='apifetchlog',
            index=models.Index(fields=['status', '-started_at'], name='api_collect_status_784cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='apifetchlog',
            index=models.Index(fields=['api_config', '-started_at'], name='api_collect_api_con_35096a_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_date'], name='api_collect_publish_a6814e_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['doi'], name='api_collect_doi_039c83_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['api_source', '-fetched_at'], name='api_collect_api_sou_e4cbcd_idx'),
        ),
    ]
