# Generated by Django 6.0.2 on 2026-02-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_collecter', '0002_apifetchlog_apisourceconfig_article_and_more'),
        ('webscraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyKonfig',
            fields=[
            ],
            options={
                'verbose_name': 'Proxy Konfigürasyonu',
                'verbose_name_plural': 'Proxy Konfigürasyonları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('webscraping.proxyconfig',),
        ),
        migrations.CreateModel(
            name='ScrapeIcerik',
            fields=[
            ],
            options={
                'verbose_name': 'Scrape Edilen İçerik',
                'verbose_name_plural': 'Scrape Edilen İçerikler',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('webscraping.scrapedcontent',),
        ),
        migrations.CreateModel(
            name='ScrapeLogu',
            fields=[
            ],
            options={
                'verbose_name': 'Scrape Logu',
                'verbose_name_plural': 'Scrape Logları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('webscraping.scrapelog',),
        ),
        migrations.CreateModel(
            name='ScraperKonfig',
            fields=[
            ],
            options={
                'verbose_name': 'Scraper Konfigürasyonu',
                'verbose_name_plural': 'Scraper Konfigürasyonları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('webscraping.scraperconfig',),
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='api_collect_doi_039c83_idx',
        ),
        migrations.RemoveField(
            model_name='apisourceconfig',
            name='search_query',
        ),
        migrations.RemoveField(
            model_name='apisourceconfig',
            name='source_type',
        ),
        migrations.AddField(
            model_name='apifetchlog',
            name='request_body',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='apifetchlog',
            name='request_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='apifetchlog',
            name='request_method',
            field=models.CharField(default='GET', max_length=10),
        ),
        migrations.AddField(
            model_name='apifetchlog',
            name='response_size_bytes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apifetchlog',
            name='response_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apifetchlog',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='api_key_header_name',
            field=models.CharField(blank=True, default='X-API-Key', help_text='API key header adı (örn: X-API-Key, Authorization)', max_length=100),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='api_key_param_name',
            field=models.CharField(blank=True, default='api_key', help_text='API key parametre adı (örn: api_key, apikey)', max_length=100),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='auth_type',
            field=models.CharField(choices=[('none', 'No Authentication'), ('api_key_header', 'API Key in Header'), ('api_key_param', 'API Key as URL Parameter'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Authentication')], default='none', help_text='Kimlik doğrulama türü', max_length=20),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='author_field_type',
            field=models.CharField(choices=[('string', 'String (virgülle ayrılmış)'), ('array', 'Array/List'), ('object_array', 'Object Array (name field içeren)')], default='array', help_text='Yazar alanının formatı', max_length=20),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='author_name_field',
            field=models.CharField(blank=True, default='name', help_text='Object array ise, isim alanının adı', max_length=100),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='custom_headers',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Özel HTTP headers (JSON formatında)\n        Örnek: {\n            "User-Agent": "MyApp/1.0",\n            "Accept": "application/json"\n        }\n        '),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='date_format',
            field=models.CharField(blank=True, default='%Y-%m-%d', help_text='Tarih formatı (Python strftime formatı, örn: %Y-%m-%d, %d/%m/%Y)', max_length=50),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='default_search_query',
            field=models.TextField(blank=True, help_text='Varsayılan arama sorgusu'),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='description',
            field=models.TextField(blank=True, help_text='API açıklaması'),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='field_mappings',
            field=models.JSONField(default=dict, help_text='\n        Alan eşleştirmeleri (JSON formatında)\n        API\'den gelen alanları standart alanlara eşleştir\n        Örnek: {\n            "title": "title",\n            "abstract": "description",\n            "authors": "author_list",\n            "published_date": "pub_date",\n            "external_id": "id",\n            "url": "link",\n            "doi": "doi",\n            "categories": "subjects"\n        }\n        Nokta notasyonu desteklenir: "metadata.title"\n        '),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='http_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', help_text='HTTP metodu', max_length=10),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='last_error',
            field=models.TextField(blank=True, help_text='Son hata mesajı'),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='last_error_at',
            field=models.DateTimeField(blank=True, help_text='Son hata zamanı', null=True),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='max_retries',
            field=models.IntegerField(default=3, help_text='Hata durumunda maksimum deneme sayısı'),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='pagination_param_name',
            field=models.CharField(blank=True, default='page', help_text='Sayfa numarası parametresi adı', max_length=50),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='pagination_start',
            field=models.IntegerField(default=1, help_text='Sayfalama başlangıç değeri (0 veya 1)'),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='query_params',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Dinamik sorgu parametreleri (JSON formatında)\n        Örnek: {\n            "q": "{search_query}",\n            "limit": "{max_results}",\n            "sort": "date",\n            "format": "json"\n        }\n        Değişkenler: {search_query}, {max_results}, {categories}\n        '),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='rate_limit_per_hour',
            field=models.IntegerField(default=1000, help_text='Saatte maksimum istek sayısı'),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='request_body_template',
            field=models.JSONField(blank=True, default=dict, help_text='POST isteği için body template (JSON)'),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='request_delay_seconds',
            field=models.FloatField(default=1.0, help_text='İstekler arası bekleme süresi (saniye)'),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='response_data_path',
            field=models.CharField(default='results', help_text="\n        Yanıttaki veri dizisinin yolu (nokta notasyonu)\n        JSON örnek: 'data.items' veya 'results'\n        XML örnek: 'feed.entry' veya 'rss.channel.item'\n        ", max_length=500),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='response_format',
            field=models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('rss', 'RSS Feed')], default='json', help_text='API yanıt formatı', max_length=10),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='supports_pagination',
            field=models.BooleanField(default=False, help_text='API sayfalama destekliyor mu?'),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='timeout_seconds',
            field=models.IntegerField(default=60, help_text='İstek timeout süresi (saniye)'),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='total_requests_made',
            field=models.IntegerField(default=0, help_text='Toplam yapılan istek sayısı'),
        ),
        migrations.AddField(
            model_name='apisourceconfig',
            name='verify_ssl',
            field=models.BooleanField(default=True, help_text='SSL sertifikası doğrulaması'),
        ),
        migrations.AlterField(
            model_name='apifetchlog',
            name='articles_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apifetchlog',
            name='articles_saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apifetchlog',
            name='articles_skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apifetchlog',
            name='articles_updated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apifetchlog',
            name='error_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='apifetchlog',
            name='request_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='apifetchlog',
            name='request_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='apifetchlog',
            name='status',
            field=models.CharField(choices=[('queued', 'Kuyrukta'), ('started', 'Başladı'), ('fetching', 'Çekiliyor'), ('parsing', 'Parse Ediliyor'), ('saving', 'Kaydediliyor'), ('success', 'Başarılı'), ('partial', 'Kısmi Başarı'), ('failed', 'Başarısız'), ('timeout', 'Zaman Aşımı'), ('rate_limited', 'Rate Limit')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='apisourceconfig',
            name='api_key',
            field=models.CharField(blank=True, help_text='API anahtarı', max_length=500),
        ),
        migrations.AlterField(
            model_name='apisourceconfig',
            name='base_url',
            field=models.URLField(help_text='API endpoint URL (örn: https://api.example.com/search)'),
        ),
        migrations.AlterField(
            model_name='apisourceconfig',
            name='fetch_interval_hours',
            field=models.IntegerField(default=6, help_text='Kaç saatte bir otomatik çekilecek'),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='external_id',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='callbackconfig',
            name='endpoint_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='callbackconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='callbackconfig',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='callbackconfig',
            name='retry_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='callbackconfig',
            name='timeout_seconds',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='callbackconfig',
            name='webhook_secret',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='callbacklog',
            name='event_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='callbacklog',
            name='request_payload',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='callbacklog',
            name='response_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='callbacklog',
            name='response_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callbacklog',
            name='retry_attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='webhookreceiver',
            name='headers',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='webhookreceiver',
            name='payload',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='webhookreceiver',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='webhookreceiver',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='webhookreceiver',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
