# Generated by Django 6.0 on 2026-03-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_collecter', '0003_proxykonfig_scrapeicerik_scrapelogu_scraperkonfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, help_text='Resim URL', max_length=1000),
        ),
    ]
