# Generated by Django 6.0.2 on 2026-04-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleNLPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=500, unique=True)),
                ('source_table', models.CharField(choices=[('article', 'API Article'), ('scraped', 'Scraped Content')], default='article', max_length=50)),
                ('keywords', models.JSONField(default=list, help_text='Extracted keywords with scores')),
                ('entities', models.JSONField(default=dict, help_text='Named entities (persons, orgs, locations)')),
                ('topic_id', models.IntegerField(blank=True, null=True)),
                ('topic_confidence', models.FloatField(blank=True, null=True)),
                ('topic_words', models.JSONField(default=list)),
                ('embedding', models.JSONField(default=list, help_text='384-dim sentence embedding vector')),
                ('embedding_model', models.CharField(default='all-MiniLM-L6-v2', max_length=100)),
                ('token_count', models.IntegerField(default=0)),
                ('language', models.CharField(default='en', max_length=10)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article NLP Profile',
                'verbose_name_plural': 'Article NLP Profiles',
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['topic_id'], name='NLP_Process_topic_i_c08f3c_idx'), models.Index(fields=['source_table', 'external_id'], name='NLP_Process_source__40fa10_idx')],
            },
        ),
    ]
