# Generated by Django 5.0 on 2026-02-07 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Scraper için benzersiz isim', max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('arxiv', 'arXiv'), ('openalex', 'OpenAlex'), ('tubitak', 'TÜBİTAK'), ('yok_tez', 'YÖK Tez Merkezi'), ('dergipark', 'DergiPark'), ('google_scholar', 'Google Scholar'), ('researchgate', 'ResearchGate'), ('academia', 'Academia.edu'), ('custom', 'Özel Kaynak')], help_text='Kaynak türü', max_length=50)),
                ('scraper_type', models.CharField(choices=[('api', 'API Tabanlı'), ('html', 'HTML Parsing'), ('selenium', 'Selenium (JavaScript)'), ('rss', 'RSS Feed')], default='html', help_text='Scraping yöntemi', max_length=20)),
                ('base_url', models.URLField(help_text='Temel URL')),
                ('login_url', models.URLField(blank=True, help_text="Giriş URL'i (gerekiyorsa)")),
                ('username', models.CharField(blank=True, help_text='Giriş kullanıcı adı', max_length=255)),
                ('password', models.CharField(blank=True, help_text='Giriş şifresi', max_length=255)),
                ('search_query', models.TextField(help_text='Arama sorgusu/anahtar kelimeler')),
                ('categories', models.TextField(blank=True, help_text='Kategoriler (virgülle ayrılmış)')),
                ('date_filter_start', models.DateField(blank=True, help_text='Başlangıç tarihi filtresi', null=True)),
                ('date_filter_end', models.DateField(blank=True, help_text='Bitiş tarihi filtresi', null=True)),
                ('max_results', models.IntegerField(default=100, help_text='Maksimum sonuç sayısı')),
                ('max_pages', models.IntegerField(default=10, help_text='Maksimum sayfa sayısı')),
                ('delay_between_requests', models.FloatField(default=2.0, help_text='İstekler arası bekleme (saniye)')),
                ('timeout_seconds', models.IntegerField(default=30, help_text='İstek timeout süresi')),
                ('user_agent', models.TextField(default='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36', help_text='User-Agent header')),
                ('custom_headers', models.JSONField(blank=True, default=dict, help_text='Özel HTTP headers')),
                ('selectors', models.JSONField(blank=True, default=dict, help_text='CSS/XPath seçicileri')),
                ('scrape_interval_hours', models.IntegerField(default=24, help_text='Kaç saatte bir çalışacak')),
                ('is_active', models.BooleanField(default=True, help_text='Aktif/Pasif')),
                ('last_run', models.DateTimeField(blank=True, help_text='Son çalışma zamanı', null=True)),
                ('next_run', models.DateTimeField(blank=True, help_text='Sonraki planlanan çalışma', null=True)),
                ('total_items_scraped', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0, help_text='Başarı oranı (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scraper Konfigürasyonu',
                'verbose_name_plural': 'Scraper Konfigürasyonları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Sırada'), ('started', 'Başladı'), ('running', 'Çalışıyor'), ('success', 'Başarılı'), ('partial', 'Kısmi Başarı'), ('failed', 'Başarısız'), ('timeout', 'Zaman Aşımı'), ('cancelled', 'İptal Edildi')], default='queued', max_length=20)),
                ('pages_scraped', models.IntegerField(default=0, help_text='Taranan sayfa sayısı')),
                ('items_found', models.IntegerField(default=0, help_text='Bulunan öğe sayısı')),
                ('items_saved', models.IntegerField(default=0, help_text='Kaydedilen öğe sayısı')),
                ('items_updated', models.IntegerField(default=0, help_text='Güncellenen öğe sayısı')),
                ('items_skipped', models.IntegerField(default=0, help_text='Atlanan öğe sayısı')),
                ('items_failed', models.IntegerField(default=0, help_text='Başarısız öğe sayısı')),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True, help_text='Tam hata izi')),
                ('failed_urls', models.JSONField(blank=True, default=list, help_text="Başarısız URL'ler")),
                ('requests_made', models.IntegerField(default=0, help_text='Yapılan istek sayısı')),
                ('bytes_downloaded', models.BigIntegerField(default=0, help_text='İndirilen veri (byte)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('triggered_by', models.CharField(default='scheduled', help_text='manual/scheduled/api', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Ek notlar')),
                ('scraper_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='webscraping.scraperconfig')),
            ],
            options={
                'verbose_name': 'Scrape Logu',
                'verbose_name_plural': 'Scrape Logları',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Kaynak sistemdeki ID', max_length=255)),
                ('source_url', models.URLField(help_text='Kaynak URL')),
                ('title', models.TextField(help_text='Başlık')),
                ('abstract', models.TextField(blank=True, help_text='Özet/Açıklama')),
                ('content_type', models.CharField(choices=[('article', 'Makale'), ('thesis', 'Tez'), ('conference', 'Konferans'), ('book', 'Kitap'), ('book_chapter', 'Kitap Bölümü'), ('report', 'Rapor'), ('funding', 'Fon/Hibe'), ('event', 'Etkinlik'), ('other', 'Diğer')], default='article', max_length=50)),
                ('authors', models.JSONField(default=list, help_text='Yazarlar listesi')),
                ('affiliations', models.JSONField(blank=True, default=list, help_text='Kurumlar')),
                ('published_date', models.DateField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('issn', models.CharField(blank=True, max_length=50)),
                ('isbn', models.CharField(blank=True, max_length=50)),
                ('categories', models.JSONField(default=list, help_text='Kategoriler')),
                ('keywords', models.JSONField(default=list, help_text='Anahtar kelimeler')),
                ('language', models.CharField(default='en', help_text='Dil kodu', max_length=10)),
                ('pdf_url', models.URLField(blank=True)),
                ('has_full_text', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, help_text='Konum (konferans için)', max_length=255)),
                ('event_date', models.DateField(blank=True, help_text='Etkinlik tarihi', null=True)),
                ('deadline', models.DateField(blank=True, help_text='Son başvuru tarihi', null=True)),
                ('amount', models.CharField(blank=True, help_text='Fon miktarı', max_length=100)),
                ('raw_data', models.JSONField(default=dict, help_text='Orijinal scrape edilen veri')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False, help_text='NLP ile işlendi mi?')),
                ('scrape_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='webscraping.scrapelog')),
                ('scraper_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_contents', to='webscraping.scraperconfig')),
            ],
            options={
                'verbose_name': 'Scrape Edilen İçerik',
                'verbose_name_plural': 'Scrape Edilen İçerikler',
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='ProxyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Proxy adı', max_length=100)),
                ('proxy_type', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('socks4', 'SOCKS4'), ('socks5', 'SOCKS5')], default='http', max_length=10)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_working', models.BooleanField(default=True, help_text='Son kontrolde çalışıyor muydu?')),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('fail_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scrapers', models.ManyToManyField(blank=True, related_name='proxies', to='webscraping.scraperconfig')),
            ],
            options={
                'verbose_name': 'Proxy Konfigürasyonu',
                'verbose_name_plural': 'Proxy Konfigürasyonları',
            },
        ),
        migrations.AddIndex(
            model_name='scrapelog',
            index=models.Index(fields=['status', '-started_at'], name='webscraping_status_e5f0ec_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapelog',
            index=models.Index(fields=['scraper_config', '-started_at'], name='webscraping_scraper_78fc9d_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedcontent',
            index=models.Index(fields=['content_type', '-scraped_at'], name='webscraping_content_302223_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedcontent',
            index=models.Index(fields=['external_id'], name='webscraping_externa_54a265_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedcontent',
            index=models.Index(fields=['doi'], name='webscraping_doi_ba0781_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedcontent',
            index=models.Index(fields=['-published_date'], name='webscraping_publish_3b4494_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scrapedcontent',
            unique_together={('scraper_config', 'external_id')},
        ),
    ]
