# Generated by Django 5.0 on 2026-03-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperconfig',
            name='cookies',
            field=models.JSONField(blank=True, default=dict, help_text='Özel çerezler'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='date_format',
            field=models.CharField(blank=True, help_text='Tarih formatı (Python strftime). Boş bırakılırsa otomatik algılanır.', max_length=50),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='delay_between_pages',
            field=models.FloatField(default=3.0, help_text='Sayfalar arası bekleme (saniye)'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='login_password_field',
            field=models.CharField(blank=True, default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='login_username_field',
            field=models.CharField(blank=True, default='username', max_length=100),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='pagination_start_page',
            field=models.IntegerField(default=1, help_text='Başlangıç sayfa numarası (genellikle 1)'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='pagination_template',
            field=models.CharField(blank=True, help_text='[URL_INCREMENT] {page} placeholder içeren tam URL şablonu. Örnek: https://www.ankara.edu.tr/kategori/haberler/{page}  Temel URL çalışmadığında kullanın (sayfa numarasız URL mevcut değilse).', max_length=1000),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='pagination_type',
            field=models.CharField(choices=[('none', 'Sayfalama Yok'), ('next_button', 'Sonraki Buton/Link'), ('page_numbers', 'Sayfa Numaraları'), ('url_pattern', 'URL Şablonu ({page} içinde)'), ('url_increment', 'URL Increment — Sayfa No Path İçinde')], default='none', help_text='Sayfalama stratejisi', max_length=20),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='pagination_url_pattern',
            field=models.CharField(blank=True, help_text='[url_pattern] {page} placeholder içeren URL. Örnek: https://site.com/sayfa/{page}', max_length=500),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='requires_login',
            field=models.BooleanField(default=False, help_text='Giriş gerekiyor mu?'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='selector_type',
            field=models.CharField(choices=[('css', 'CSS'), ('xpath', 'XPath'), ('mixed', 'Mixed')], default='css', help_text='Seçici türü', max_length=10),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='stop_when_empty',
            field=models.BooleanField(default=True, help_text='Sayfada hiç öğe bulunamazsa otomatik dur. URL_INCREMENT için önerilir.'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='verify_ssl',
            field=models.BooleanField(default=True, help_text='SSL sertifikalarını doğrula'),
        ),
    ]
