# Generated by Django 6.0 on 2026-03-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0002_add_url_increment_pagination'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedcontent',
            name='image_url',
            field=models.URLField(blank=True, help_text='Resim URL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='scrapedcontent',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
