# Generated by Django 6.0.2 on 2026-03-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0003_scrapedcontent_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperconfig',
            name='search_query',
            field=models.TextField(blank=True, default='', help_text='Arama sorgusu/anahtar kelimeler'),
        ),
    ]
