# Generated by Django 6.0.2 on 2026-03-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0004_alter_scraperconfig_search_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperconfig',
            name='scraper_type',
            field=models.CharField(choices=[('api', 'API Tabanlı'), ('html', 'HTML Parsing'), ('selenium', 'Selenium (JavaScript)'), ('playwright', 'Playwright (Chrome/WebKit)'), ('rss', 'RSS Feed')], default='html', help_text='Scraping yöntemi', max_length=20),
        ),
    ]
