# Generated by Django 6.0 on 2026-03-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0005_alter_scraperconfig_scraper_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperconfig',
            name='content_category',
            field=models.CharField(choices=[('magazine', 'Magazin'), ('article', 'Makale'), ('architecture', 'Mimari'), ('news', 'Haber Sitesi'), ('academic', 'Akademik'), ('other', 'Diğer')], default='news', help_text='İçerik Kategorisi', max_length=50),
        ),
    ]
