# Generated by Django 6.0 on 2026-03-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0007_scraperconfig_max_results_per_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperconfig',
            name='enable_multi_step',
            field=models.BooleanField(default=False, help_text='Çok aşamalı taramayı aktif et (örn: Önce linkleri topla, sonra her linke git)'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='enable_query_encoding',
            field=models.BooleanField(default=False, help_text='Arama terimlerini URL formatına dönüştür (quote)'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='enable_relative_url_fix',
            field=models.BooleanField(default=True, help_text="Göreceli linkleri tam URL'e dönüştür (urljoin)"),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='max_depth',
            field=models.IntegerField(default=2, help_text='Tarama derinliği (Multi-step için)'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='max_pages_per_step',
            field=models.IntegerField(default=10, help_text='Aşama başına maksimum sayfa limiti'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='step1_selectors',
            field=models.JSONField(blank=True, default=dict, help_text='Aşama 1: Linkleri keşfetmek için kullanılacak seçiciler'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='step2_selectors',
            field=models.JSONField(blank=True, default=dict, help_text='Aşama 2: Detay sayfasından veri çekmek için kullanılacak seçiciler'),
        ),
    ]
