# Generated by Django 6.0 on 2026-03-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0008_scraperconfig_enable_multi_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperconfig',
            name='enable_infinite_scroll',
            field=models.BooleanField(default=False, help_text='Sonsuz kaydırma (Infinite Scroll) aktif mi?'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='scroll_count',
            field=models.IntegerField(default=5, help_text='Kaç kez aşağı kaydırılacak?'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='scroll_delay',
            field=models.IntegerField(default=2000, help_text='Kaydırmalar arası bekleme (ms)'),
        ),
    ]
