# Generated by Django 6.0 on 2026-03-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0009_scraperconfig_enable_infinite_scroll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperconfig',
            name='scroll_count',
            field=models.IntegerField(blank=True, default=5, help_text='Kaç kez aşağı kaydırılacak?'),
        ),
        migrations.AlterField(
            model_name='scraperconfig',
            name='scroll_delay',
            field=models.IntegerField(blank=True, default=2000, help_text='Kaydırmalar arası bekleme (ms)'),
        ),
    ]
